name: Publish PBIX to Power BI

on:
  push:
    branches:
      - master  # Adjust branch if needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust Python version if needed

    - name: Publish PBIX to Power BI
      env:
        PB_USERNAME: ${{ secrets.PB_USERNAME }}
        PB_PASSWORD: ${{ secrets.PB_PASSWORD }}
      run: |
        pip install powerbiclient
        python publish_pbix.py
